### ISSUE TITLE
Make parser submodule in XRD plugin

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#123]
put the parser and the related nomad_plugin.yaml file in a subfolder to have the possibility to import either the schema or the parser separately. Take inspiration from the movpe_IKZ plugin to see the init.py imports and everything

**Comment by ka-sarthak** [comment]
The issue was moved to `nomad-measurements`
https://github.com/FAIRmat-NFDI/nomad-measurements/issues/82
