### ISSUE TITLE
create a submodule for XRD plugin inside the IKZ plugin

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#126]
Create a new submodule in our IKZ_plugin where you inherit all the XRD classes, you include them in the general IKZ category, and you do not basically add anything to that. We can discuss more, if needed

**Comment by aalbino2** [comment]
did we decide to close this oder?

**Comment by ka-sarthak** [comment]
We decided that once the other plugins from @aalbino2 and @hampusnasstrom are successfully merged into the IKZ plugin folder, we can proceed with adding XRD plugin too
