### ISSUE TITLE
remove all the relevant classes from the "other" category

### ISSUE THREAD

**Issue by andreaa93** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#129]
We need to figure out this aspect.

The RawFile entries are probably polluting each specific category so they should be left in "Other"

What do you think? 

@ka-sarthak @hampusnasstrom

**Comment by hampusnasstrom** [comment]
Yeah, I think they can be left in Other or ideally hidden if possible.

**Comment by aalbino2** [comment]
Ok great, so for now I will delete any category attribute from all the raw files, maybe in the future they will also be hidden

This is addressed in PR #138
