### ISSUE TITLE
let's make solution preparation

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#143]
Hi guys @RoteKekse @hampusnasstrom 

after checking Micha's classes, I firmly believe we can share a common ground of classes, at least these:
Solution, SolutionPreparation, SolutionWasching, SolutionProperties, SolutionStorage

Why? Because - together to underlying semantics - if we can share a common ground of classes, this is even more fair than sharing only a semantics that one then have to figure out across someone else's schema

We may have a brief very practical meeting on these ideas, if you would feel like that

**Comment by aalbino2** [comment]
I pin here the repos:

https://github.com/nomad-hzb/nomad-baseclasses/blob/main/baseclasses/solution.py
https://github.com/nomad-hzb/nomad-baseclasses/blob/main/baseclasses/mxene_solution.py

**Comment by RoteKekse** [comment]
I think it is  great if nomad has baseclasses for this out of the box, but i am not sure if i would use them, because for me it is easier and more flexible if i have full control on these schemas on this detail level.

I am ok though with having a common results section which can then be used to populate the data for solutions. so that the data is interoperable in nomad.

**Comment by aalbino2** [comment]
I just copy-pasted your classes so far. So it would be just a matter from your side of inheriting them instead of having them in your code

**Comment by RoteKekse** [comment]
yes even if they are exactly the same, i am not sure if this is good. it has been very beneficial if we can just start developing schemas to our needs and then by semantic annotation later make the data fairer

being dependent with the schemas does not fell like an advantages. it just adds coordination and therefore complexity

**Comment by aalbino2** [comment]
We foresee to arrive at a plateau with data modeling, not keeping changing things, so it means these part of data model will be more and more steady the more we go on in the future. Also it is such an easy part of data modeling this "solution" one...

**Comment by RoteKekse** [comment]
For nomad can’t this just happen in the results section?

**Comment by RoteKekse** [comment]
Yes extending it would be the idea. I mean you can develop basesections but I think using them neither means the data is fairer or less fair as long as it is annotated. So using them should be left to the local labs if it is helpful or not.

**Comment by RoteKekse** [comment]
Maybe sometimes use them and sometimes don’t . That shouldn’t impact the fairness.

**Comment by aalbino2** [comment]
It does impact it.. necessarily! Unless you have implemented some other software figuring out the similarities between two schemas retrieving their annotation and then connecting to a reasoner going through the ontology

Thank you for discussion. I'm sorry you don't wanna approach this route. Let's see what happens with time

**Comment by aalbino2** [comment]
I added the solution classes in PR #144 together to other work.

**Comment by aalbino2** [comment]
That is?

**Comment by RoteKekse** [comment]
That it has a static structure
