### ISSUE TITLE
Descriptions for quantities and sub-sections in transmission plugin

### ISSUE THREAD

**Issue by ka-sarthak** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#163]
Below you can find the tree structure of the `UVVisTransmission` measurement class, `TransmissionSpectrophotometer` class, and `TransmissionSample` class. We need concise descriptions for each quantity and sub-section in them.

Some descriptions are already available (these are italicized), but they are mere suggestions. Feel free to suggest better ones. 

Ideally, the description should be 1-2 lines long and clear to understand.
 
### `UVVisTransmission` measurement class
- `method` (`str`)
- `user` (`str`)
	- description: _Name of the analyst/user_
- subsection: `UVVisTransmissionResult`
	- `transmittance` (`list[float]`)
	- `absorbance` (`list[float]`)
	- `wavelength` (`list[float]`)
- subsection: `TransmissionSettings`
	- `ordinate_type` (`MEnum(['%T', 'A'])`)
	- `sample_beam_position` (`MEnum(['Front', 'Rear'])`)
	- `common_beam_mask` (`int`)
	- `common_beam_depolarizer` (`bool`)
	- `polarizer_angle` (`float`)
	- subsection: `Accessory`
		- `polarizer` (`bool`)
			- description: _True if the polarizer is used, else False._
		- `aperture` (`float`)
	- subsection: `Monochromator`
		- `monochromator_change_point` (`list[float]`)
		- subsection: `SlitWidth`
			- description: _Slit width value over a wavelength range._
			- `slit_width_servo` (`bool`)
				- description: _True if slit width servo is on, i.e., the slit width varies over the wavelength range, else False_.
	- subsection: `Lamp`
		- `d2_lamp` (`bool`)
		- `tungsten_lamp` (`bool`)
		- `lamp_change_point` (`list[float]`)
	- subsection: `Detector`
		- `module` (`MEnum(['three detector module', '150-mm integrating sphere'])`)
		- `detector_change_point` (`list[float]`)
		- subsection: `NIRGain`
			- description: _NIR gain over a wavelength range._
		- subsection: `IntegrationTime`
			- description: _Integration time over a wavelength range._
	- subsection: `Attenuator`
		- `sample` (`int`)
			- description: _Sample beam attenuation in %_
		- `reference` (`int`)
			- description: _Reference beam attenuation in %_

### `TransmissionSpectrophotometer` instrument class
- `serial_number` (`str`)
- `software_version` (`str`)

### `TranmissionSample` sample class
- `name` (`str`)
- `lab_id` (`str`)
	- description: *Sample ID.*
- `chemical_composition` (`str`)
- `length` (`float`)
	- description: *Length (or thickness) of the sample in mm.*
- `orientation` (`str`)
        description: *Crystallographic orientation of the sample.*

**Comment by ahm531** [comment]
Hi Sarthak,
Here are some descriptions added to the quantities. I am also attaching a page from the help page of the PerkinElmer instrument software from which I got most of the text. [Here is the file](https://github.com/FAIRmat-NFDI/AreaA-data_modeling_and_schemas/files/15497622/UV-vis.help.file.pdf)

### `UVVisTransmission` measurement class
- `method` (`str`)
	- description: _Measurement technique used._
- `user` (`str`)
	- description: _Name of the analyst/user_
- subsection: `UVVisTransmissionResult`
	- `transmittance` (`list[float]`)
	       - description: _List of transmittance values (%)._
	- `absorbance` (`list[float]`)
	       - description: _List of absorbance values._
	- `wavelength` (`list[float]`)
	       - description: _List of wavelength values (nm)._
- subsection: `TransmissionSettings`
	- `ordinate_type` (`MEnum(['%T', 'A'])`)
	       - description: _Specifies whether the ordinate (y-axis) of the measurement data is displayed as percent transmittance (%T) or absorbance (A)._
	- `sample_beam_position` (`MEnum(['Front', 'Rear'])`)
	       - description: _Position of the sample beam: either the front or the back of the sample chamber._
	- `common_beam_mask` (`int`)
	       - description: _Beam mask settings: 100% means the mask is fully open and 100% of the beam passes. 0% means the mask is closed and no light passes._
	- `common_beam_polarizer` (`bool`)
	       - description: _Optional accessory used to depolarize the radiation coming from the monochromator (True if used, , else False)._
	- `polarizer_angle` (`float`)
               - description: _Angle of the polarizer in degrees._
	- subsection: `Accessory`
		- `polarizer` (`bool`)
			- description: _ Optional accessory to polarize or depolarize the light beam entering the sample (True if used, else False)._
		- `aperture` (`float`)
                        - description: _Diameter of the aperture in millimeters._
	- subsection: `Monochromator`
		- `monochromator_change_point` (`list[float]`)
			- description: _The wavelength at which the monochromator changes settings._
		- subsection: `SlitWidth`
			- description: _Slit width value in nm._
			- `slit_width_servo` (`bool`)
				- description: _True if slit width servo is on, i.e. the system monitors the reference beam energy and adjusts the slits to avoid over-saturation of the detectors. _
	- subsection: `Lamp`
		- `d2_lamp` (`bool`)
			- description: _True when the deuterium lamp is used (typically covers UV ranges from approximately 160 nm to 400 nm)._
		- `tungsten_lamp` (`bool`)
			- description: _True when the tungsten lamp is used (typically covering the visible to near-infrared range from about 320 nm to 2500 nm)._
		- `lamp_change_point` (`list[float]`)
			- description: _The wavelength at which beams are switched between deuterium and tungsten lamps. _
	- subsection: `Detector`
		- `module` (`MEnum(['three detector module', '150-mm integrating sphere'])`)
			- description: _Type of detector module used._
		- `detector_change_point` (`list[float]`)
			- description: _The wavelength at which the detector module changes. _
		- subsection: `NIRGain`
			- description: _The gain factor for the detector._
			- description: _NIR gain over a wavelength range._
		- subsection: `IntegrationTime`
			- description: _Integration time over a wavelength range._
	- subsection: `Attenuator`
		- `sample` (`int`)
			- description: _Sample beam attenuation in %_
		- `reference` (`int`)
			- description: _Reference beam attenuation in %_

### `TransmissionSpectrophotometer` instrument class
- `serial_number` (`str`)
	- description: _Spectrophotometer serial number._ 
- `software_version` (`str`)
	- description: _Software version used by the spectrophotometer._

### `TranmissionSample` sample class
- `name` (`str`)
	- description: _Descriptive name of the sample_
- `lab_id` (`str`)
	- description: _An ID string that is unique at least for the lab that produced this sample._
- `chemical_composition` (`str`)
	- description: _Chemical composition of the sample_
- `length` (`float`)
	- description: *Length (or thickness) of the sample in mm.*
- `orientation` (`str`)
        description: *Crystallographic orientation of the sample.*

**Comment by ka-sarthak** [comment]
@ahm531 Great work! Thanks a lot for your input and sharing the file from Perkin Elmer. 

Some question:

- Is the `polarizer_angle` the one for the `Accessory.polarizer`. If that's the case, then we can move this quantity into the `Accessory` sub-section. Can you comment on this?
- The description for `Accessory.polarizer` includes "Optional accessory to polarize or depolarize the light beam". This is a bit confusing. Do you mean that two Accessories can be added to either polarize (using a `polarizer`) or depolarize (using a `depolarizer`) the light beam? In this case, do you think we should move `common_beam_depolarizer` to this sub-section? 

Some remarks:

- `common_beam_polarizer` is actually `common_beam_depolarizer`. This is a typo in my comment above, will edit it there. But I think you wrote the correct description anyways!  
- I think the descriptions should be unit-agnostic. I myself am a culprit of adding something like `Length (or thickness) of the sample in mm`. But given that one toggle the units on the GUI, and the conversion is taken care by NOMAD, puting the units in description gives a false notion to the user that they should always stick with this unit. On other hand, specifying that a certain dimensionless quantity is a percentage or ratio in the description is totally reasonable.

**Comment by ka-sarthak** [comment]
@budschi @ahm531 Is there a need to specify the detector materials used in `Detector` sub-section? In the [Perkin Elmer help guide](https://github.com/FAIRmat-NFDI/AreaA-data_modeling_and_schemas/files/15497622/UV-vis.help.file.pdf), they write "The instrument uses a single detector (photomultiplier for UV/Vis and PbS or InGaAs for NIR)"

**Comment by ahm531** [comment]
> Is the polarizer_angle the one for the Accessory.polarizer. If that's the case, then we can move this quantity into the Accessory sub-section. Can you comment on this?

- I guess so. It also confused me at first that they were separated. 

> The description for Accessory.polarizer includes "Optional accessory to polarize or depolarize the light beam". This is a bit confusing. Do you mean that two Accessories can be added to either polarize (using a polarizer) or depolarize (using a depolarizer) the light beam? In this case, do you think we should move common_beam_depolarizer to this sub-section?

There is an accessory that can either polarize or depolarize the light. [see here](https://resources.perkinelmer.com/lab-solutions/resources/docs/prd-006991A-04-LAMBDA650-1050PolarizerDepolarizerOptions.pdf)
- I also quote from the manual "The optional depolarizer/polarizer mounts inside the sample chamber. It is used to polarize or depolarize the light beam entering the sample. A switch on the accessory sets it to depolarizer or polarizer".
- I don't think the common_beam_depolarizer (CBD) should be moved to this subsection. The CBD is installed inside the spectrometer and works on the common light beam coming from the source (before it is separated into the reference beam and the sample beam in the sample compartment) The polarizer/depolarizer is installed in the sample compartment.

**Comment by ahm531** [comment]
> @budschi @ahm531 Is there a need to specify the detector materials used in Detector sub-section? In the [Perkin Elmer help guide](https://github.com/FAIRmat-NFDI/AreaA-data_modeling_and_schemas/files/15497622/UV-vis.help.file.pdf), they write "The instrument uses a single detector (photomultiplier for UV/Vis and PbS or InGaAs for `NIR)"

I think the individual types of detectors are standard. However, for generality, I guess there should be another module in this list `module (MEnum(['three detector module', '150-mm integrating sphere'])`. The three detector module is only available in Lambda 1050. However, the instrument versions have only two detectors (I'm not sure what that mode would be called).

**Comment by ahm531** [comment]
Just checked one of my ASC files (Lambda 950) it has the following line (25) about the detector:
`CommonBeamDepol,RBeamAtt,SBeamAtt,**uv/vis/nir detector**`

Do you think we should also include this in the module quantity?

**Comment by hirokitanaka-ikz** [comment]
@ka-sarthak @ahm531
Hi,
concerning the polarizers and depolarizers, I know that some devices have a depolarizer inside (we can activate and deactivate it). Our Lambda1050 does not have it. Alternatively we can purchase a pair of depolarizers which can be installed at the position of the polarizers.

**Comment by ahm531** [comment]
@ka-sarthak 
Both Lambda 950 and 1050 measure the same range (175-3300 nm) covering UV/Vis/NIR light.

- Lambda 950 uses two detectors (PMT and PbS) for good performance.

- Lambda 1050 has a "three detector module" with PMT, PbS and InGaAs. This additional detector (InGaAs) makes it much better at picking up weak signals in the near infrared (NIR) region (about 900-1700 nm).

Now, translating `uv/vis/nir detector` to `three-detector module` doesn't seem accurate, especially since the Lambda 950 doesn't have three detectors.   The term "three-detector module" is specific to the configuration of the Lambda 1050. However, I don't have solution to this at the moment, but would be happy to discuss and compare the asc files from both instruments.

Also, having the three-detector module would mean that there are two wavelength change points when someone is measuring from 175 nm to 3300 nm. I'm wondering if this is accounted for in the code (or planned).

![image](https://github.com/FAIRmat-NFDI/AreaA-data_modeling_and_schemas/assets/115071866/db96f0ab-ac2e-4689-b1e6-083d23f6dbf3)

**Comment by ka-sarthak** [comment]
@ahm531 @hirokitanaka-ikz Thank you both for sharing detailed differences in detector between the two instruments. We should make the schema adaptable to the two versions for instrument. 

- Use `EnumEditQuantity` for `detector_module` which gives us a dropdown menu to select the module. Here we can add `uv/vis/nir`, `uv/vis/nir three-detector-module`, `150mm Sphere`
- Based on the name of the instrument taken from the .asc file (Lambda 1050 or Lambda 950), the respective detector module will be selected. 
- Add the information about the individual detector (for eg., Three detector module has PMT, InGaAs, and PbS detectors) in the descriptions of the module.
- @ahm531 the number of detector change point is variable, and depends on the data file. So in case of normal detector, there will be only one change point, in case of three-detector module, there will be two change points.
- @hirokitanaka-ikz In the guide, they mention that CBD is an optional accessory along with Polarizer/Depolarizer (or Pol/Depol). We can add both these in the accessory sub-section.
- move `polarizer_angle` to the accessory sub-section under Pol/Depol. @hirokitanaka-ikz is this polarizer angle related to the polarizer inside the sample chamber?

**Comment by ka-sarthak** [comment]
Thanks for making this discussion lively! Let's find some time this week to finalize on these points.
