### ISSUE TITLE
Making HALL a standalone plugin

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#173]
after finishing the points at #16 

the code must be spun off this repo, made standalone, and inheriting from nomad-measurements

@budschi what do you think? Can it be a standalone repo in IKZ-Berlin?

**Comment by budschi** [comment]
yes! I have a bunch of measurements there already: IKZ Omega ´Theta, Raman. I migh talso move RTG Sims there after refactoring it
