### ISSUE TITLE
Transfer RTG SIMS Plugin to new Plugin Mechanism

### ISSUE THREAD

**Issue by budschi** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#187]
https://github.com/FAIRmat-NFDI/AreaA-data_modeling_and_schemas/tree/main/RTG_SIMS
still uses the old plugin mechanism and needs to be updated.

**Comment by aalbino2** [comment]
if I make it a standalone repo, in which organization should it be put @budschi?
