### ISSUE TITLE
remove IKZ plugin from this repo 

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#195]
I will place it as a standalone repo in the IKZ organization.

Just FYI @budschi @hampusnasstrom @ka-sarthak

**Comment by budschi** [comment]
Once you are done with this I would like to take that as a an opportunity to update the production oasis at ikz

**Comment by aalbino2** [comment]
This plugin has been moved to the IKZ organization, follow the link

https://github.com/IKZ-Berlin/nomad-ikz-plugin
