### ISSUE TITLE
FileEditQuantities can't fish from uploads

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#42]
Don't you think that whenever a prepare a FileEditQuantity where I drag and drop stuff I should be able to search for a raw file I may already have uploaded? So far one can only press the little cloud icon and upload it from the pc

![Screenshot from 2023-04-14 17-00-10](https://user-images.githubusercontent.com/95371554/232080884-74632806-ddbd-4784-be0d-73895e9f668e.png)

**Comment by aalbino2** [comment]
If yes, I may open an issue on gitlab, just prefer to share the idea here before

**Comment by budschi** [comment]
ok, could be practical

**Comment by aalbino2** [comment]
let's forget it for now..
