### ISSUE TITLE
PureSubstance

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#69]
Hi, I just started using the full structure @hampusnasstrom designed, I'm wondering if in The PureSubstance it is correct that the elemental_composition is in the parent section and not in PureSubstanceSection, where the conceptual description of the substance is

Let's discuss this!

I know that it is there due to inheritance from system, it is not super well fitting here though

![Screenshot from 2023-10-06 11-26-19](https://github.com/FAIRmat-NFDI/AreaA-data_modeling_and_schemas/assets/95371554/85ea961b-6e60-406c-aeb0-c21bc84b8a80)

**Comment by hampusnasstrom** [comment]
I see your point but if it's up to me I would still keep it this way. I think the elemental composition will rarely be filled/viewed manually in the ELN but rather calculated from formulae and components and then used for searches. What do you think @budschi?

**Comment by budschi** [comment]
> I see your point but if it's up to me I would still keep it this way. I think the elemental composition will rarely be filled/viewed manually in the ELN but rather calculated from formulae and components and then used for searches. What do you think @budschi?

My experience is also like @hampusnasstrom described, elemental_composition gets populated automatically without user input. Where would you put exactly @aalbino2 ? It serves the findabilty in searches nicely,
