### ISSUE TITLE
Jupyter Notebook Analysis Plugin

### ISSUE THREAD

**Issue by budschi** [FAIRmat-NFDI/AreaA-data_modeling_and_schemas#92]
Notes from Jupyter Notebook Analysis demo and discussion in the Area A TF meeting on 8.1.2024:
    * Jupyter analysis classes instead of choosing analysis type
    * creating a schema category
    * also having a solution when applying analysis on data of the same upload!?
    * best practice? instantiate Jupyter analysis schema and then attach Notebook?
    * make Notebook searchable
    * get rid of reset button if possible
    * Results: write into separate entry!? as NOMAD sections. create by custom schema on the fly, also create archive on the fly
    * should be moved to the base sections
    

_Originally posted by @budschi in https://github.com/FAIRmat-NFDI/AreaA-data_modeling_and_schemas/discussions/91_

**Comment by budschi** [comment]
* allow change of jupyter notebook file name

**Comment by ka-sarthak** [comment]
TODO 
- [ ] Get entry_ids of the input entries through an api call to the analysis archive within the notebook. This will avoid the use of `reset` predefined cells.
- [ ] Include the name of the analysis eln and analysis type in the name of the generated Jupyter. This allows to have multiple generated notebooks (each associated to one analysis eln) in the same upload without overwriting.
- [ ] Make a separate class for each analysis type. This way the type of the analysis within a given eln will always be fixed.

**Comment by ka-sarthak** [comment]
Issues related to `nomad-analysis` will be dealt here https://github.com/FAIRmat-NFDI/nomad-analysis/issues
